---
title: "Plasmidsaurus RNAseq EBV+ limma"
author: "Kaitlyn Tremble"
date: "2026-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r block0: setup}
rm(list = ls())

base_dir <- "~/Desktop/sequencing/2025_11_Plasmidsaurus_RNA_Seq"
code_dir <- file.path(base_dir, "sorelle-lab-ezh2-project")
data_dir <- file.path(base_dir, "1_data/")
pipe_dir <- file.path(base_dir, "2_pipeline/limma/")
out_dir <- file.path(base_dir, "3_outputs/limma/")
setwd(code_dir)

source('0_functions.R')

# packages
using('BiocManager', 
      'DOSE',
      'enrichplot',
      'fgsea',
      'ggrepel', 
      'ggupset',
      'ggVennDiagram',
      'htmlwidgets',
      'msigdbr',
      'pheatmap',
      'RColorBrewer',
      'Seurat',  
      'tidyverse')

bioc_using('biomaRt', 
           'clusterProfiler',
           'edgeR',
           'limma',
           'org.Hs.eg.db',
           'Rsubread')


# can change these
logfc_limit <- 0.6
pvalue_limit <- 0.05

```

```{r}
norm_counts <- readRDS(paste0(base_dir, '/2_pipeline/norm_counts.RDS'))

metadata <- read.csv(paste0(data_dir, 'samples.csv'),
                           stringsAsFactors = TRUE)

cell_lines <- unique(metadata$cell_line)
treatments <- unique(metadata$treatment)
```

```{r}
# tutorial: https://f1000research.com/articles/5-1408/v3

my_cell <- 'ibl1'
idx <- norm_counts$samples$cells == my_cell
# use the logical vector to subset the DGEList object
counts_subset <- norm_counts[, idx]

meta_subset <- filter(metadata, cell_line == my_cell)
design <- model.matrix(~ treatment, data = meta_subset)
rownames(design) <- colnames(counts_subset) #ensure proper grouping here



```

