---
title: "Plasmidsaurus RNAseq EBV+ edgeR"
author: "Kaitlyn Tremble"
date: "2026-01-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

NOTES: 
This code begins with an expected counts file which is organized with replicates appearing in adjacent columns
File organization and naming convention is essential for running properly

```{r block0: setup}
rm(list = ls())

base_dir <- "~/Desktop/sequencing/2025_11_Plasmidsaurus_RNA_Seq"
code_dir <- file.path(base_dir, "sorelle-lab-ezh2-project")
data_dir <- file.path(base_dir, "data")
pipe_dir <- file.path(base_dir, "edgeR_pipeline")
out_dir <- file.path(base_dir, "edgeR_outputs")
setwd(code_dir)

source('functions.R')

# packages
using('BiocManager', 
      'DOSE',
      'enrichplot',
      'fgsea',
      'ggrepel', 
      'ggupset',
      'ggVennDiagram',
      'htmlwidgets',
      'msigdbr',
      'pheatmap',
      'RColorBrewer',
      'Seurat',  
      'tidyverse')

bioc_using('biomaRt', 
           'clusterProfiler',
           'edgeR',
           'org.Hs.eg.db',
           'Rsubread')


# can change these
logfc_limit <- 0.6
pvalue_limit <- 0.05

```

```{r block1: getting DEGs by treatment status}

# here I use for loops to iterate through all the different samples
# the main work is a function since the experiment design is consistent

# COMPARING TREATMENT GROUPS WITHIN CELL LINE
cell_lines <- c('akata', 'cf5', 'ibl1', 'lcl', 'mutu')
treatment_comparisons <- c('2v1', '3v1', '3v2')


# edgeR to find DEGs 
## see BioConductor edgeR user manual
for (x in cell_lines){
  fit <- edger_fit_genes(x) #this estimates dispersions for each cell line
  for (y in treatment_comparisons){
    edger_degs(fit, x, y) #this compares treatment status to get DEGs from fit
  }
}
```

```{r block2: analyzing DEGs by treatment effects}
# using DEGs from block1
cell_lines <- c('akata', 'cf5', 'ibl1', 'lcl', 'mutu')
treatment_comparisons <- c('2v1', '3v1', '3v2')

# volcano plots
## can label viral genes using label = 'viral'
## or label custom gene list using label = 'custom' and gene = your_list
## can also use hover = TRUE to make interactive plot
for (x in cell_lines){
  for (y in treatment_comparisons){
    degs_volcano_plot(x, y)
  }
}


# making venn diagrams to compare DEGs between cell lines
compare_cells <- c('akata', 'mutu') #change for different comparisons
for (y in treatment_comparisons){
  degs_venn_diagram(compare_cells, y, 'up')
  degs_venn_diagram(compare_cells, y, 'down')
}


# pathway enrichment analysis bar plots using MSigDB
## can change collection & subcollection
## use msigdbr_collections() to view options 
## biological processes: 'C5' 'GO:BP'
for (x in cell_lines){
  msigdb_pathway_enrichment_analysis(x, '3v1')
}

```

```{r block3: getting DEGs by cell line}
## this is doing block1 by hand because the experimental design is different

# reorganizing the counts matrix
counts <- read.csv(paste0(data_dir, '/exp_counts/counts_all.csv'))
counts <- counts[,1:25]
counts_dmso <- counts[,c(1:5,14:17)]
counts_ms177 <- counts[,c(1,6:9,18:21)]
counts_taz <- counts[,c(1,10:13,22:25)]


groups <- c(1,1,1,1,2,2,2,2)
dge <- DGEList(counts_taz, group = groups) # creating DGE list
keep <- filterByExpr(dge) #filtering out low counts
dge <- dge[keep, , keep.lib.sizes = FALSE]
norm_counts <- normLibSizes(dge)


metadata <- read.csv(file.path(data_dir, 'samples_cell.csv'),
                           stringsAsFactors = TRUE)
design <- model.matrix( ~ cell_line, data = metadata)
rownames(design) <- colnames(norm_counts)
y <- estimateDisp(norm_counts, design, robust = TRUE)
fit <- glmQLFit(y, design, robust = TRUE)

#cf5 vs akata
lrt <- glmLRT(fit, coef = 2)

df <- as.data.frame(lrt)

# converting ENSEMBL IDs to gene symbol
genes <- df$gene_id
annots <- select(org.Hs.eg.db,
                 keys = genes,
                 columns = "SYMBOL",
                 keytype = "ENSEMBL")

df <- merge(df, annots, by.x = "gene_id", by.y = "ENSEMBL")
df$SYMBOL <- ifelse(is.na(df$SYMBOL), df$gene_id, df$SYMBOL)

#removing genes with PValue = 0
df <- filter(df, PValue != 0)

# annotating DEGs as no/up/down regulated
df$diffexpressed <- "NO"
df$diffexpressed[df$logFC > logfc_limit &
                   df$PValue < pvalue_limit] <- "UP"
df$diffexpressed[df$logFC < -logfc_limit &
                   df$PValue < pvalue_limit] <- "DOWN"

treatment <- 'taz'

# saving DEG lists
## all DEGs
sorted_df <- df %>% arrange(PValue)
csv_file_path <- paste0(pipe_dir, '/degs/', treatment, "_cf5_vs_akata.csv")
write.csv(sorted_df, csv_file_path, row.names = FALSE)
## significant DEGs
sig_degs <- filter(sorted_df, diffexpressed != 'NO')
sig_path <- paste0(pipe_dir, '/degs/', treatment, "_cf5_vs_akata_sig.csv")
write.csv(sig_degs, sig_path, row.names = FALSE)
## significant up regulated DEGs
up_degs <- filter(sorted_df, diffexpressed == 'UP')
up_path <- paste0(pipe_dir, '/degs/', treatment, "_cf5_vs_akata_sig_up.csv")
write.csv(up_degs, up_path, row.names = FALSE)
## significant down regulated DEGs
down_degs <- filter(sorted_df, diffexpressed == 'DOWN')
down_path <- paste0(pipe_dir, '/degs/', treatment, "_cf5_vs_akata_sig_down.csv")
write.csv(down_degs, down_path, row.names = FALSE)



```

```{r block4: analyzing DEGs by cell line}
# repeat of block2 using DEGs from block3

# COMPARING CELL LINES WITHIN TREATMENT GROUPS (Akata vs CF5)
treatments <- c('dmso', 'ms177', 'taz')
cells_group <- 'cf5_vs_akata'


# volcano plots
for (x in treatments){
  degs_volcano_plot(x, cells_group, 'viral')
}


# making venn diagrams to compare DEGs between treatment groups
treatment_compare <- c('ms177', 'taz')

degs_venn_diagram(treatment_compare, cells_group, 'up')
degs_venn_diagram(treatment_compare, cells_group, 'down')


# MSigDB PEA
msigdb_pathway_enrichment_analysis('dmso', cells_group)
```

```{r block5: analyzing viral genes MS177 vs DMSO}
# making data frame of significantly up/down regulated viral genes annotated

# collecting & labeling all viral reads from cell line DEG lists
cell_lines <- c('akata', 'ibl1', 'lcl', 'mutu')
viral_degs <- data.frame()
for (x in cell_lines){
  df_up <- read.csv(paste0(pipe_dir, '/degs/', x, '_2v1_sig_up.csv'))
  df_up <- dplyr::select(df_up, gene_id)
  df_up <- filter(df_up, str_detect(df_up$gene_id, '^ENSG') == FALSE)
  colnames(df_up) <- paste0(x, '_up')
  df_up_long <- pivot_longer(df_up, 1, 
                        names_to = 'cell',
                        values_to = 'gene_id')
  viral_degs <- rbind(viral_degs, df_up_long)
  
  df_down <- read.csv(paste0(pipe_dir, '/degs/', x, '_2v1_sig_down.csv'))
  df_down <- dplyr::select(df_down, gene_id)
  df_down <- filter(df_down, str_detect(df_down$gene_id, '^ENSG') == FALSE)
  colnames(df_down) <- paste0(x, '_down')
  df_down_long <- pivot_longer(df_down, 1, 
                        names_to = 'cell',
                        values_to = 'gene_id')
  viral_degs <- rbind(viral_degs, df_down_long)
  
  print(paste0(x, ' upregulated viral genes: ', nrow(df_up)))
  print(paste0(x, ' downregulated viral genes: ', nrow(df_down)))
}

# adding EBV gene annotation
ebv_annot <- read.csv(file.path(data_dir, 'ebv_annot.csv'))
df_merge <- merge(viral_degs, ebv_annot, by.x='gene_id', by.y='gene_id', all.x = TRUE)

df_merge <- dplyr::select(df_merge, cell, gene_id, everything())
df_merge$kinetics <- factor(df_merge$kinetics,
                            levels = c('immediate_early', 'early', 'leaky', 'late', 'latent'))

df_merge <- separate(df_merge, 1, into = c('cell', 'direction'), sep = '_')

# save annotated viral DEGs
#write.csv(df_merge, file.path(pipe_dir, 'degs/viral_sig_2v1.csv'), 
#          row.names = FALSE)

# START HERE if list already made
#df_merge <- read.csv(file.path(pipe_dir, 'degs/viral_sig_2v1.csv'))

# making labels pretty for graph
df_pretty <- df_merge %>% mutate(cell = toupper(cell))
df_pretty <- df_pretty %>% mutate(kinetics = str_to_sentence(kinetics))
df_pretty$kinetics <- factor(df_pretty$kinetics,
                            levels = c('Immediate Early', 'Early', 'Leaky', 'Late', 'Latent'))
df_pretty <- df_pretty %>% mutate(direction = ifelse(direction == 'up', 'Upregulated', 'Downregulated'))

plottitle <- 'Differentially Expressed EBV Genes in MS177 vs DMSO'
# viral gene bar graph
ggplot(df_pretty, aes(fill = kinetics, x = cell)) +
  geom_bar() +
  labs(title = plottitle,
       x = 'Cell Line',
       y = 'Gene Count',
       fill = 'Kinetics') +
  facet_wrap(~ direction) +
  theme_bw() 

ggsave(file.path(out_dir, 'ebv_genes_2v1.png'))
```

```{r block6: analyzing viral genes TAZ vs DMSO}
# repeat of block5 with TAZ instead of MS177
# making data frame of significantly up/down regulated viral genes annotated

# collecting & labeling all viral reads from cell line DEG lists
cell_lines <- c('akata', 'ibl1', 'lcl', 'mutu')
viral_degs <- data.frame()
for (x in cell_lines){
  df_up <- read.csv(paste0(pipe_dir, '/degs/', x, '_3v1_sig_up.csv'))
  df_up <- dplyr::select(df_up, gene_id)
  df_up <- filter(df_up, str_detect(df_up$gene_id, '^ENSG') == FALSE)
  colnames(df_up) <- paste0(x, '_up')
  df_up_long <- pivot_longer(df_up, 1, 
                        names_to = 'cell',
                        values_to = 'gene_id')
  viral_degs <- rbind(viral_degs, df_up_long)
  
  df_down <- read.csv(paste0(pipe_dir, '/degs/', x, '_3v1_sig_down.csv'))
  df_down <- dplyr::select(df_down, gene_id)
  df_down <- filter(df_down, str_detect(df_down$gene_id, '^ENSG') == FALSE)
  colnames(df_down) <- paste0(x, '_down')
  df_down_long <- pivot_longer(df_down, 1, 
                        names_to = 'cell',
                        values_to = 'gene_id')
  viral_degs <- rbind(viral_degs, df_down_long)
  
  print(paste0(x, ' upregulated viral genes: ', nrow(df_up)))
  print(paste0(x, ' downregulated viral genes: ', nrow(df_down)))
}

# adding EBV gene annotation
ebv_annot <- read.csv(file.path(data_dir, 'ebv_annot.csv'))
df_merge <- merge(viral_degs, ebv_annot, by.x='gene_id', by.y='gene_id', all.x = TRUE)

df_merge <- dplyr::select(df_merge, cell, gene_id, everything())
df_merge$kinetics <- factor(df_merge$kinetics,
                            levels = c('immediate_early', 'early', 'leaky', 'late', 'latent'))

df_merge <- separate(df_merge, 1, into = c('cell', 'direction'), sep = '_')

# save annotated viral DEGs
#write.csv(df_merge, file.path(pipe_dir, 'degs/viral_sig_3v1.csv'), 
#          row.names = FALSE)

# START HERE if list already made
#df_merge <- read.csv(file.path(pipe_dir, 'degs/viral_sig_3v1.csv'))

# making labels pretty for graph
df_pretty <- df_merge %>% mutate(cell = toupper(cell))
df_pretty <- df_pretty %>% mutate(kinetics = str_to_sentence(kinetics))
df_pretty$kinetics <- factor(df_pretty$kinetics,
                            levels = c('Immediate Early', 'Early', 'Leaky', 'Late', 'Latent'))
df_pretty <- df_pretty %>% mutate(direction = ifelse(direction == 'up', 'Upregulated', 'Downregulated'))

plottitle <- 'Differentially Expressed EBV Genes in TAZ vs DMSO'
# viral gene bar graph
ggplot(df_pretty, aes(fill = kinetics, x = cell)) +
  geom_bar() +
  labs(title = plottitle,
       x = 'Cell Line',
       y = 'Gene Count',
       fill = 'Kinetics') +
  facet_wrap(~ direction) +
  theme_bw() 

ggsave(file.path(out_dir, 'ebv_genes_3v1.png'))
```

```{r block7: GSEA pt1}
# gene set enrichment analysis using fgsea & MSigDB
## plots top 20 pathways
## can change collection & subcollection
## use msigdbr_collections() to view options 
## biological process: 'C5' 'GO:BP'

cell_lines <- c('akata', 'cf5', 'ibl1', 'lcl', 'mutu')
for (x in cell_lines){
  msigdb_gsea_main_plot(x, '2v1')
}

cells_group <- 'cf5_vs_akata'
treatments <- c('dmso', 'ms177', 'taz')
for (x in treatments){
  msigdb_gsea_main_plot(x, cells_group)
}

```

```{r block8: GSEA pt2}
# making enrichment plots for pathways of interest using fgsea
## here I'm making plots for TNFa signaling & apoptosis

# run fgsea
akata_gsea <- msigdb_gsea('akata', '2v1')
# look at pathways & decide which to plot
akata_gsea@result[["ID"]]
# enrichment plot
msigdb_gsea_enrich_plot('akata_2v1', akata_gsea, 7)
msigdb_gsea_enrich_plot('akata_2v1', akata_gsea, 11)

cf5_gsea <- msigdb_gsea('cf5', '2v1')
cf5_gsea@result[["ID"]]
msigdb_gsea_enrich_plot('cf5_2v1', cf5_gsea, 5)
msigdb_gsea_enrich_plot('cf5_2v1', cf5_gsea, 7)

ibl1_gsea <- msigdb_gsea('ibl1', '2v1')
ibl1_gsea@result[["ID"]]
msigdb_gsea_enrich_plot('ibl1_2v1', ibl1_gsea, 2)
msigdb_gsea_enrich_plot('ibl1_2v1', ibl1_gsea, 9)

lcl_gsea <- msigdb_gsea('lcl', '2v1')
lcl_gsea@result[["ID"]]
msigdb_gsea_enrich_plot('lcl_2v1', lcl_gsea, 5)
msigdb_gsea_enrich_plot('lcl_2v1', lcl_gsea, 12)

mutu_gsea <- msigdb_gsea('mutu', '2v1')
mutu_gsea@result[["ID"]]
```

```{r block9: edgeR on all samples for correlation}
# normalizing expected counts
counts <- read.csv(paste0(data_dir, '/exp_counts/counts_all.csv'))
groups <- rep(1:15, each = 4)
dge <- DGEList(counts, group = groups) # creating DGE list
keep <- filterByExpr(dge) #filtering out low counts
dge <- dge[keep, , keep.lib.sizes = FALSE]
norm_counts <- normLibSizes(dge)

# design matrix
metadata <- read.csv(file.path(data_dir, 'samples.csv'),
                           stringsAsFactors = TRUE)
metadata$group <- paste(metadata$cell_line, metadata$treatment, sep = ".")
design <- model.matrix( ~ 0 + group, data = metadata)
rownames(design) <- colnames(norm_counts)
design


# saving norm counts
norm_df <- as.data.frame(norm_counts)
# write.csv(norm_df, paste0(data_dir, '/exp_counts/norm_counts.csv'))

# making MDS plot
my_shapes <- 15:17
shape_vec <- rep(rep(my_shapes, each = 4), times = 5)
my_colors <- c('deepskyblue', 'mediumorchid1', 'maroon1', 'green3', 'firebrick1')
color_vec <- rep(my_colors, each = 12)
  
png(paste0(out_dir, "/samples/all_mds.png"), 
    width = 8, 
    height = 6, 
    units = 'in',
    res = 1200,
    pointsize = 12) 
plotMDS(norm_counts, col= color_vec, pch= shape_vec)
legend("topright", col=my_colors, legend=c("Akata","CF5", "IBL1", "LCL", "Mutu"),
       text.col=my_colors)
legend("bottomright", pch=my_shapes, legend=c("DMSO", "MS177", "TAZ"))
title('MDS Plot of RNAseq Samples')
dev.off()

# runnning correlation tests on norm counts
samp_labels <- paste(metadata$group, metadata$rep, sep = ".")
norm_matrix <- norm_df[,2:61]
colnames(norm_matrix) <- samp_labels

spearman_res <- cor(norm_matrix, method = 'spearman')
pheatmap(spearman_res,
         fontsize = 5)

pearson_res <- cor(norm_matrix, method = 'pearson')
pheatmap(pearson_res,
         fontsize = 5)


# estimating the dispersion of the gene expression MS177 vs DMSO
filter(norm_counts)
y <- estimateDisp(norm_counts, design, robust = TRUE)
png(paste0(out_dir, "/samples/all_est_disp.png"), 
    width = 800, 
    height = 600, 
    units = "px") 
plotBCV(y)
dev.off()

```
